name = input("Enter your name:")
age = int(input("Enter your age:"))
age_int = int(age)
print(type(age))
print(type(age_int))
print("Hello " + name + "! You are " + str(age))
# print(type(age) + type(age_int))
print(age*5)